# -*- coding: utf-8 -*-
"""SKYN — Catalogue produits dermo-cosmétiques (marché français).

PROVENANCE DES DONNÉES
----------------------
Chaque entrée correspond à un produit réellement commercialisé en pharmacie /
parapharmacie française (ou sur des sites FR courants type Newpharma, Easypara,
Pharma GDD, Redcare, Nocibé, Lookfantastic pour The Ordinary). Les noms
commerciaux, marques et compositions ont été vérifiés sur les sites de marque et
les fiches produit des distributeurs français (août 2026).

LIMITES — À LIRE AVANT TOUTE EXPLOITATION
-----------------------------------------
1. CONCENTRATIONS. Le champ `pct` n'est renseigné QUE lorsque la marque ou le
   distributeur communique explicitement le pourcentage. Dans tous les autres cas
   il vaut `None` : l'INCI ne donne pas les dosages et il ne faut RIEN inventer.
   Un `None` signifie « présent dans la formule, dosage non communiqué », jamais
   « absent ».
2. PRIX. `price_eur` est un ordre de grandeur du prix public conseillé constaté
   en parapharmacie FR. Les prix varient fortement d'une officine à l'autre et
   dans le temps : à traiter comme une fourchette indicative, pas comme un tarif.
   Ils servent surtout à l'algorithme pour proposer des routines « budget » vs
   « premium ».
3. NIVEAUX DE PREUVE. `evidence.level` qualifie L'ACTIF principal du produit, pas
   le produit fini. Aucune marque citée ici n'a fait l'objet, dans ce fichier,
   d'une extrapolation de résultat chiffré.
      - "A" : actif dont l'efficacité dans l'indication est établie par des essais
              cliniques randomisés et repris dans les recommandations
              dermatologiques (peroxyde de benzoyle, rétinoïdes, acide azélaïque,
              acide salicylique, niacinamide, photoprotection).
      - "B" : actif avec des données cliniques réelles mais plus limitées
              (zinc, PHA/gluconolactone, céramides, acide hyaluronique,
              panthénol, licochalcone A, thiamidol).
      - "C" : intérêt essentiellement cosmétique / de confort, données publiques
              faibles ou uniquement fournies par la marque.
   Les champs `source` renvoient volontairement à des classes d'actifs ou à des
   référentiels généraux (SFD, monographies, RCP ANSM) plutôt qu'à des études
   nommées : aucune référence bibliographique précise n'est citée car elle ne
   pourrait pas être garantie exacte ici.
4. USAGE MÉDICAL. Certains produits (peroxyde de benzoyle) sont des MÉDICAMENTS
   délivrés en pharmacie, sans ordonnance obligatoire mais avec conseil
   officinal. Ils sont marqués par `family = "benzoyl_peroxide"` et un
   `irritation` élevé : l'application doit toujours renvoyer vers un avis
   pharmacien/dermatologue et ne jamais se substituer à une consultation.
5. Ce catalogue N'EST PAS un avis médical. Acné sévère, nodulaire, ou résistante
   après 3 mois : orientation dermatologue obligatoire côté application.

CONVENTIONS DE CHAMPS
---------------------
- `step`      : "nettoyant" | "traitement" | "serum" | "hydratant" | "protection" | "masque"
- `moment`    : "am" | "pm" | "both"
- `targets`   : poids 0.0-1.0 par préoccupation ; clés admises :
                acne_active, comedons, post_acne_marks, sebum, pores, redness,
                sensitivity, dehydration, dullness, pigmentation, texture,
                barrier_damage, aging
- `skin_types`: "grasse" | "mixte" | "normale" | "seche" | "sensible"
- `avoid_if`  : vocabulaire contrôlé — "grossesse", "allaitement",
                "peau_tres_sensible", "rosacee", "eczema_actif",
                "allergie_aspirine", "phototype_5_6", "moins_de_15_ans",
                "peau_lesee"
- `family`    : famille d'actif utilisée pour la détection de conflits
- `irritation`: 0.0 (très bien toléré) → 1.0 (fortement irritant, introduction
                très progressive obligatoire)
"""

from __future__ import annotations

__all__ = ["PRODUCTS"]


PRODUCTS = [
    # =====================================================================
    # NETTOYANTS
    # =====================================================================
    {
        "id": "cerave-gel-moussant-nettoyant",
        "name": "Gel Moussant Nettoyant",
        "brand": "CeraVe",
        "step": "nettoyant",
        "moment": "both",
        "actives": [
            {"inci": "Niacinamide", "common": "niacinamide (vitamine B3)", "pct": None},
            {"inci": "Ceramide NP / Ceramide AP / Ceramide EOP", "common": "céramides essentiels", "pct": None},
            {"inci": "Sodium Hyaluronate", "common": "acide hyaluronique", "pct": None},
        ],
        "targets": {"sebum": 0.5, "pores": 0.3, "barrier_damage": 0.3, "dehydration": 0.2},
        "skin_types": ["normale", "mixte", "grasse"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "ceramide",
        "price_eur": 11.90,
        "irritation": 0.05,
        "evidence": {
            "level": "B",
            "note": "Nettoyant sans savon à pH physiologique enrichi en céramides : les céramides topiques aident à limiter la perte insensible en eau et l'altération de la barrière induite par les tensioactifs.",
            "source": "Données cliniques sur les céramides topiques et la fonction barrière",
        },
        "url": "https://www.cerave.fr/nos-produits/nettoyants/gel-moussant-nettoyant",
    },
    {
        "id": "cerave-lotion-nettoyante-hydratante",
        "name": "Lotion Nettoyante Hydratante",
        "brand": "CeraVe",
        "step": "nettoyant",
        "moment": "both",
        "actives": [
            {"inci": "Ceramide NP / Ceramide AP / Ceramide EOP", "common": "céramides essentiels", "pct": None},
            {"inci": "Sodium Hyaluronate", "common": "acide hyaluronique", "pct": None},
            {"inci": "Glycerin", "common": "glycérine", "pct": None},
        ],
        "targets": {"dehydration": 0.5, "barrier_damage": 0.5, "sensitivity": 0.4},
        "skin_types": ["seche", "normale", "sensible"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "ceramide",
        "price_eur": 12.50,
        "irritation": 0.03,
        "evidence": {
            "level": "B",
            "note": "Nettoyant sans rinçage agressif : formule non moussante bien tolérée sur peau sèche ou fragilisée par un traitement anti-acnéique desséchant.",
            "source": "Données cliniques sur les céramides topiques et la fonction barrière",
        },
        "url": "https://www.cerave.fr/nos-produits/nettoyants/lotion-nettoyante-hydratante",
    },
    {
        "id": "cerave-gel-moussant-anti-imperfections",
        "name": "Gel Moussant Anti-Imperfections (Blemish Control)",
        "brand": "CeraVe",
        "step": "nettoyant",
        "moment": "both",
        "actives": [
            {"inci": "Salicylic Acid", "common": "acide salicylique (BHA)", "pct": 2.0},
            {"inci": "Niacinamide", "common": "niacinamide", "pct": None},
            {"inci": "Kaolin", "common": "argile blanche", "pct": None},
            {"inci": "Ceramide NP", "common": "céramides", "pct": None},
        ],
        "targets": {"acne_active": 0.5, "comedons": 0.6, "sebum": 0.6, "pores": 0.5, "texture": 0.3},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": ["allergie_aspirine", "peau_tres_sensible"],
        "conflicts_with": ["benzoyl_peroxide"],
        "family": "bha",
        "price_eur": 13.50,
        "irritation": 0.25,
        "evidence": {
            "level": "A",
            "note": "L'acide salicylique est un kératolytique lipophile dont l'action comédolytique dans l'acné légère à modérée est documentée ; en nettoyant, le temps de contact est court, l'effet est donc plus modeste qu'en soin sans rinçage.",
            "source": "Recommandations acné - Société Française de Dermatologie",
        },
        "url": "https://www.cerave.fr/nos-produits/nettoyants",
    },
    {
        "id": "lrp-effaclar-gel-moussant-purifiant",
        "name": "Effaclar Gel Moussant Purifiant",
        "brand": "La Roche-Posay",
        "step": "nettoyant",
        "moment": "both",
        "actives": [
            {"inci": "Zinc PCA", "common": "zinc PCA", "pct": None},
            {"inci": "Aqua Thermalis (La Roche-Posay)", "common": "eau thermale", "pct": None},
        ],
        "targets": {"sebum": 0.6, "pores": 0.4, "acne_active": 0.3, "comedons": 0.3},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "zinc",
        "price_eur": 13.50,
        "irritation": 0.12,
        "evidence": {
            "level": "B",
            "note": "Le zinc PCA dispose de données cliniques limitées mais réelles sur la régulation de la production de sébum ; le nettoyant reste un geste de support, pas un traitement de l'acné.",
            "source": "Monographie zinc topique - usage séborégulateur",
        },
        "url": "https://www.laroche-posay.fr/gammes/visage/effaclar",
    },
    {
        "id": "avene-cleanance-gel-nettoyant",
        "name": "Cleanance Gel Nettoyant",
        "brand": "Avène",
        "step": "nettoyant",
        "moment": "both",
        "actives": [
            {"inci": "Silybum Marianum Extract", "common": "extrait de chardon-marie (silymarine)", "pct": None},
            {"inci": "Avene Aqua", "common": "eau thermale d'Avène", "pct": None},
        ],
        "targets": {"sebum": 0.5, "pores": 0.3, "sensitivity": 0.3, "acne_active": 0.2},
        "skin_types": ["grasse", "mixte", "sensible"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "soothing",
        "price_eur": 12.50,
        "irritation": 0.08,
        "evidence": {
            "level": "C",
            "note": "Gel sans savon pensé pour les peaux grasses réactives ; l'extrait de chardon-marie relève d'une revendication de marque, sans données cliniques indépendantes solides.",
            "source": "Composition publiée par la marque",
        },
        "url": "https://www.eau-thermale-avene.fr/peau-a-imperfections/cleanance",
    },
    {
        "id": "avene-cleanance-hydra-creme-lavante",
        "name": "Cleanance Hydra Crème Lavante Apaisante",
        "brand": "Avène",
        "step": "nettoyant",
        "moment": "both",
        "actives": [
            {"inci": "Avene Aqua", "common": "eau thermale d'Avène", "pct": None},
            {"inci": "Glycerin", "common": "glycérine", "pct": None},
        ],
        "targets": {"sensitivity": 0.6, "dehydration": 0.5, "barrier_damage": 0.5, "redness": 0.3},
        "skin_types": ["seche", "sensible", "mixte"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "soothing",
        "price_eur": 12.90,
        "irritation": 0.03,
        "evidence": {
            "level": "C",
            "note": "Nettoyant crémeux conçu pour les peaux acnéiques asséchées par un traitement local ; bénéfice attendu de confort et de tolérance.",
            "source": "Composition publiée par la marque",
        },
        "url": "https://www.eau-thermale-avene.fr/peau-a-imperfections/cleanance",
    },
    {
        "id": "bioderma-sebium-gel-moussant",
        "name": "Sébium Gel Moussant Purifiant",
        "brand": "Bioderma",
        "step": "nettoyant",
        "moment": "both",
        "actives": [
            {"inci": "Zinc Gluconate", "common": "gluconate de zinc", "pct": None},
            {"inci": "Copper Sulfate", "common": "sulfate de cuivre", "pct": None},
        ],
        "targets": {"sebum": 0.6, "pores": 0.4, "comedons": 0.3, "acne_active": 0.2},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "zinc",
        "price_eur": 12.50,
        "irritation": 0.10,
        "evidence": {
            "level": "B",
            "note": "Le zinc topique a des données limitées mais réelles en séborégulation et en soutien anti-inflammatoire ; usage ici en nettoyant quotidien.",
            "source": "Monographie zinc topique - usage séborégulateur",
        },
        "url": "https://www.bioderma.fr/c/tous-les-produits/sebium",
    },
    {
        "id": "bioderma-sensibio-h2o",
        "name": "Sensibio H2O Eau Micellaire",
        "brand": "Bioderma",
        "step": "nettoyant",
        "moment": "both",
        "actives": [
            {"inci": "Cucumis Sativus Fruit Extract", "common": "extrait de concombre", "pct": None},
            {"inci": "PEG-6 Caprylic/Capric Glycerides", "common": "micelles douces", "pct": None},
        ],
        "targets": {"sensitivity": 0.7, "redness": 0.4, "barrier_damage": 0.2},
        "skin_types": ["sensible", "normale", "seche", "mixte"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "soothing",
        "price_eur": 10.90,
        "irritation": 0.02,
        "evidence": {
            "level": "C",
            "note": "Référence de démaquillage pour peaux intolérantes : très bonne tolérance documentée en usage cosmétique, sans revendication thérapeutique.",
            "source": "Composition publiée par la marque",
        },
        "url": "https://www.bioderma.fr/c/tous-les-produits/sensibio",
    },
    {
        "id": "svr-sebiaclear-gel-moussant",
        "name": "Sebiaclear Gel Moussant",
        "brand": "SVR",
        "step": "nettoyant",
        "moment": "both",
        "actives": [
            {"inci": "Gluconolactone", "common": "gluconolactone (PHA)", "pct": None},
            {"inci": "Niacinamide", "common": "niacinamide", "pct": None},
            {"inci": "Zinc Gluconate", "common": "gluconate de zinc", "pct": None},
        ],
        "targets": {"sebum": 0.6, "comedons": 0.4, "pores": 0.4, "acne_active": 0.3},
        "skin_types": ["grasse", "mixte", "sensible"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "niacinamide",
        "price_eur": 8.98,
        "irritation": 0.12,
        "evidence": {
            "level": "B",
            "note": "Association gluconolactone (PHA, exfoliant doux) et niacinamide ; la niacinamide topique a des données solides en acné légère à modérée, ici avec un temps de contact court.",
            "source": "Données cliniques sur la niacinamide topique",
        },
        "url": "https://fr.svr.com/collections/sebiaclear",
    },
    {
        "id": "eucerin-dermopure-gel-nettoyant",
        "name": "DermoPure Gel Nettoyant",
        "brand": "Eucerin",
        "step": "nettoyant",
        "moment": "both",
        "actives": [
            {"inci": "Salicylic Acid", "common": "acide salicylique (BHA)", "pct": None},
            {"inci": "Glycyrrhiza Inflata Root Extract", "common": "licochalcone A", "pct": None},
        ],
        "targets": {"sebum": 0.6, "acne_active": 0.4, "comedons": 0.4, "redness": 0.2},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": ["allergie_aspirine"],
        "conflicts_with": [],
        "family": "bha",
        "price_eur": 8.99,
        "irritation": 0.18,
        "evidence": {
            "level": "A",
            "note": "Acide salicylique, kératolytique de référence dans l'acné rétentionnelle, associé à la licochalcone A pour l'inconfort inflammatoire.",
            "source": "Recommandations acné - Société Française de Dermatologie",
        },
        "url": "https://www.eucerin.fr/nos-produits/dermopure",
    },
    {
        "id": "topicrem-ac-gel-nettoyant-purifiant",
        "name": "AC Control Gel Nettoyant Purifiant",
        "brand": "Topicrem",
        "step": "nettoyant",
        "moment": "both",
        "actives": [
            {"inci": "Zinc Gluconate", "common": "gluconate de zinc", "pct": None},
            {"inci": "Myristyl PCA", "common": "myristyl PCA", "pct": None},
        ],
        "targets": {"sebum": 0.5, "pores": 0.3, "acne_active": 0.2},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "zinc",
        "price_eur": 8.99,
        "irritation": 0.12,
        "evidence": {
            "level": "B",
            "note": "Nettoyant séborégulateur au zinc, positionné comme geste quotidien à petit prix ; effet attendu sur la brillance plus que sur les lésions inflammatoires.",
            "source": "Monographie zinc topique - usage séborégulateur",
        },
        "url": "https://www.topicrem.com/fr/gammes/ac-control",
    },

    # =====================================================================
    # TRAITEMENTS CIBLÉS
    # =====================================================================
    {
        "id": "cutacnyl-5-gel",
        "name": "Cutacnyl 5 % gel",
        "brand": "Cutacnyl (Galderma)",
        "step": "traitement",
        "moment": "pm",
        "actives": [
            {"inci": "Benzoyl Peroxide", "common": "peroxyde de benzoyle", "pct": 5.0},
        ],
        "targets": {"acne_active": 0.95, "comedons": 0.5, "sebum": 0.2},
        "skin_types": ["grasse", "mixte", "normale"],
        "avoid_if": ["peau_tres_sensible", "eczema_actif", "peau_lesee"],
        "conflicts_with": ["retinoid", "aha", "bha", "vitamin_c"],
        "family": "benzoyl_peroxide",
        "price_eur": 6.50,
        "irritation": 0.75,
        "evidence": {
            "level": "A",
            "note": "Le peroxyde de benzoyle est un antibactérien de référence contre Cutibacterium acnes, sans induction de résistance ; efficacité sur les lésions inflammatoires établie par essais randomisés et retenue en première intention.",
            "source": "RCP Cutacnyl - base de données publique des médicaments (ANSM)",
        },
        "url": "https://base-donnees-publique.medicaments.gouv.fr/medicament/64600787/extrait",
    },
    {
        "id": "cutacnyl-2-5-gel",
        "name": "Cutacnyl 2,5 % gel",
        "brand": "Cutacnyl (Galderma)",
        "step": "traitement",
        "moment": "pm",
        "actives": [
            {"inci": "Benzoyl Peroxide", "common": "peroxyde de benzoyle", "pct": 2.5},
        ],
        "targets": {"acne_active": 0.85, "comedons": 0.45},
        "skin_types": ["grasse", "mixte", "normale", "sensible"],
        "avoid_if": ["eczema_actif", "peau_lesee"],
        "conflicts_with": ["retinoid", "aha", "bha", "vitamin_c"],
        "family": "benzoyl_peroxide",
        "price_eur": 6.20,
        "irritation": 0.55,
        "evidence": {
            "level": "A",
            "note": "Dosage à 2,5 % : efficacité comparable aux dosages supérieurs dans les essais comparatifs avec une meilleure tolérance ; c'est le dosage d'initiation à privilégier.",
            "source": "RCP Cutacnyl - base de données publique des médicaments (ANSM)",
        },
        "url": "https://base-donnees-publique.medicaments.gouv.fr/medicament/60809088/extrait",
    },
    {
        "id": "lrp-effaclar-duo-m",
        "name": "Effaclar Duo+M Soin Triple Correction",
        "brand": "La Roche-Posay",
        "step": "traitement",
        "moment": "both",
        "actives": [
            {"inci": "Salicylic Acid", "common": "acide salicylique", "pct": None},
            {"inci": "Capryloyl Salicylic Acid (LHA)", "common": "LHA", "pct": None},
            {"inci": "Niacinamide", "common": "niacinamide", "pct": None},
            {"inci": "Zinc PCA", "common": "zinc PCA", "pct": None},
            {"inci": "Procerad (ceramide)", "common": "céramide anti-marques Procerad", "pct": None},
            {"inci": "Piroctone Olamine", "common": "piroctone olamine", "pct": None},
        ],
        "targets": {"acne_active": 0.7, "comedons": 0.6, "post_acne_marks": 0.5, "sebum": 0.5, "pores": 0.4},
        "skin_types": ["grasse", "mixte", "normale"],
        "avoid_if": ["allergie_aspirine"],
        "conflicts_with": ["benzoyl_peroxide", "retinoid"],
        "family": "bha",
        "price_eur": 15.30,
        "irritation": 0.30,
        "evidence": {
            "level": "A",
            "note": "Association acide salicylique / LHA (kératolytiques) et niacinamide (anti-inflammatoire), deux actifs dont l'efficacité dans l'acné légère à modérée est documentée par essais cliniques.",
            "source": "Recommandations acné - Société Française de Dermatologie",
        },
        "url": "https://www.laroche-posay.fr/gammes/visage/effaclar",
    },
    {
        "id": "lrp-effaclar-serum-ultra-concentre",
        "name": "Effaclar Sérum Ultra Concentré",
        "brand": "La Roche-Posay",
        "step": "serum",
        "moment": "pm",
        "actives": [
            {"inci": "Salicylic Acid", "common": "acide salicylique", "pct": 1.5},
            {"inci": "Glycolic Acid", "common": "acide glycolique (AHA)", "pct": 3.5},
            {"inci": "Capryloyl Salicylic Acid (LHA)", "common": "LHA", "pct": 0.45},
            {"inci": "Niacinamide", "common": "niacinamide", "pct": None},
        ],
        "targets": {"comedons": 0.8, "acne_active": 0.6, "pores": 0.6, "texture": 0.6, "post_acne_marks": 0.4, "sebum": 0.4},
        "skin_types": ["grasse", "mixte", "normale"],
        "avoid_if": ["allergie_aspirine", "peau_tres_sensible", "grossesse"],
        "conflicts_with": ["retinoid", "benzoyl_peroxide"],
        "family": "bha",
        "price_eur": 29.90,
        "irritation": 0.50,
        "evidence": {
            "level": "A",
            "note": "Triple exfoliation acide salicylique + acide glycolique + LHA : les BHA et AHA topiques ont une efficacité comédolytique et sur le grain de peau établie par essais cliniques.",
            "source": "Recommandations acné - Société Française de Dermatologie",
        },
        "url": "https://www.laroche-posay.fr/produits-soins/effaclar/effaclar-serum-ultra-concentre-acide-salicylique-p27422.aspx",
    },
    {
        "id": "avene-cleanance-comedomed",
        "name": "Cleanance Comedomed Concentré Anti-Imperfections",
        "brand": "Avène",
        "step": "traitement",
        "moment": "both",
        "actives": [
            {"inci": "Silybum Marianum Fruit Extract (Comedoclastin)", "common": "Comedoclastin (chardon-marie)", "pct": None},
            {"inci": "Niacinamide", "common": "niacinamide", "pct": None},
        ],
        "targets": {"comedons": 0.8, "acne_active": 0.6, "sebum": 0.5, "pores": 0.4},
        "skin_types": ["grasse", "mixte", "sensible"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "niacinamide",
        "price_eur": 19.90,
        "irritation": 0.20,
        "evidence": {
            "level": "B",
            "note": "Le Comedoclastin est un extrait breveté ciblant le micro-comédon, soutenu par des travaux du laboratoire ; la présence de niacinamide apporte le seul actif à preuve forte de la formule.",
            "source": "Données cliniques sur la niacinamide topique + documentation marque",
        },
        "url": "https://www.eau-thermale-avene.fr/peau-a-imperfections/cleanance",
    },
    {
        "id": "bioderma-sebium-global",
        "name": "Sébium Global Soin Anti-Imperfections",
        "brand": "Bioderma",
        "step": "traitement",
        "moment": "both",
        "actives": [
            {"inci": "Salicylic Acid", "common": "acide salicylique", "pct": None},
            {"inci": "Zinc Gluconate", "common": "gluconate de zinc", "pct": None},
            {"inci": "Fluidactiv", "common": "complexe Fluidactiv (qualité du sébum)", "pct": None},
        ],
        "targets": {"acne_active": 0.7, "comedons": 0.6, "sebum": 0.6, "pores": 0.4},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": ["allergie_aspirine"],
        "conflicts_with": ["benzoyl_peroxide", "retinoid"],
        "family": "bha",
        "price_eur": 15.90,
        "irritation": 0.30,
        "evidence": {
            "level": "A",
            "note": "Soin quotidien associant acide salicylique (kératolytique à preuve établie) et zinc séborégulateur, dans une base non comédogène.",
            "source": "Recommandations acné - Société Française de Dermatologie",
        },
        "url": "https://www.bioderma.fr/c/tous-les-produits/sebium",
    },
    {
        "id": "bioderma-sebium-night-peel",
        "name": "Sébium Night Peel Concentré Lissant",
        "brand": "Bioderma",
        "step": "traitement",
        "moment": "pm",
        "actives": [
            {"inci": "Glycolic Acid", "common": "acide glycolique (AHA)", "pct": 15.0},
            {"inci": "Panthenol", "common": "panthénol (pro-vitamine B5)", "pct": None},
        ],
        "targets": {"texture": 0.8, "comedons": 0.6, "post_acne_marks": 0.5, "dullness": 0.5, "pores": 0.5},
        "skin_types": ["grasse", "mixte", "normale"],
        "avoid_if": ["peau_tres_sensible", "grossesse", "rosacee"],
        "conflicts_with": ["retinoid", "benzoyl_peroxide", "bha"],
        "family": "aha",
        "price_eur": 19.90,
        "irritation": 0.60,
        "evidence": {
            "level": "A",
            "note": "Acide glycolique à 15 % : les AHA topiques ont une efficacité documentée sur le renouvellement épidermique, le grain de peau et les marques post-inflammatoires ; photosensibilisation, SPF indispensable le lendemain.",
            "source": "Monographie acides alpha-hydroxylés (AHA) topiques",
        },
        "url": "https://www.bioderma.fr/c/tous-les-produits/sebium",
    },
    {
        "id": "svr-sebiaclear-active",
        "name": "Sebiaclear Active Gel",
        "brand": "SVR",
        "step": "traitement",
        "moment": "both",
        "actives": [
            {"inci": "Gluconolactone", "common": "gluconolactone (PHA)", "pct": 14.0},
            {"inci": "Niacinamide", "common": "niacinamide", "pct": 4.0},
            {"inci": "Salicylic Acid", "common": "acide salicylique", "pct": None},
        ],
        "targets": {"acne_active": 0.75, "comedons": 0.7, "sebum": 0.6, "pores": 0.6, "post_acne_marks": 0.4},
        "skin_types": ["grasse", "mixte", "sensible"],
        "avoid_if": ["allergie_aspirine"],
        "conflicts_with": ["benzoyl_peroxide", "retinoid"],
        "family": "niacinamide",
        "price_eur": 15.90,
        "irritation": 0.35,
        "evidence": {
            "level": "A",
            "note": "Niacinamide à 4 % (anti-inflammatoire à preuve établie) associée à un PHA à 14 % et à l'acide salicylique ; les PHA exfolient plus doucement que les AHA, intérêt sur peau réactive.",
            "source": "Données cliniques sur la niacinamide topique",
        },
        "url": "https://fr.svr.com/collections/sebiaclear",
    },
    {
        "id": "svr-sebiaclear-cicapeel",
        "name": "Sebiaclear Cicapeel Soin Ciblé",
        "brand": "SVR",
        "step": "traitement",
        "moment": "pm",
        "actives": [
            {"inci": "Gluconolactone", "common": "gluconolactone (PHA)", "pct": None},
            {"inci": "Niacinamide", "common": "niacinamide", "pct": None},
            {"inci": "Salicylic Acid", "common": "acide salicylique", "pct": None},
        ],
        "targets": {"acne_active": 0.7, "post_acne_marks": 0.6, "texture": 0.3},
        "skin_types": ["grasse", "mixte", "sensible"],
        "avoid_if": ["allergie_aspirine"],
        "conflicts_with": ["benzoyl_peroxide"],
        "family": "bha",
        "price_eur": 6.89,
        "irritation": 0.35,
        "evidence": {
            "level": "B",
            "note": "Soin localisé sur bouton et marque récente : actifs à preuve établie (salicylique, niacinamide) mais application ponctuelle, donc bénéfice attendu limité à la lésion traitée.",
            "source": "Recommandations acné - Société Française de Dermatologie",
        },
        "url": "https://fr.svr.com/collections/sebiaclear",
    },
    {
        "id": "the-ordinary-niacinamide-10-zinc-1",
        "name": "Niacinamide 10% + Zinc 1%",
        "brand": "The Ordinary",
        "step": "serum",
        "moment": "both",
        "actives": [
            {"inci": "Niacinamide", "common": "niacinamide", "pct": 10.0},
            {"inci": "Zinc PCA", "common": "zinc PCA", "pct": 1.0},
        ],
        "targets": {"sebum": 0.7, "pores": 0.6, "acne_active": 0.5, "post_acne_marks": 0.4, "redness": 0.3},
        "skin_types": ["grasse", "mixte", "normale"],
        "avoid_if": ["peau_tres_sensible"],
        "conflicts_with": [],
        "family": "niacinamide",
        "price_eur": 5.50,
        "irritation": 0.25,
        "evidence": {
            "level": "A",
            "note": "La niacinamide topique améliore les lésions inflammatoires d'acné et la production de sébum dans plusieurs essais randomisés ; à 10 % certaines peaux réactives rougissent, tester progressivement.",
            "source": "Données cliniques sur la niacinamide topique",
        },
        "url": "https://theordinary.com/fr-fr/niacinamide-10-zinc-1-serum-100436.html",
    },
    {
        "id": "the-ordinary-azelaic-acid-10",
        "name": "Azelaic Acid Suspension 10%",
        "brand": "The Ordinary",
        "step": "traitement",
        "moment": "both",
        "actives": [
            {"inci": "Azelaic Acid", "common": "acide azélaïque", "pct": 10.0},
        ],
        "targets": {"acne_active": 0.75, "post_acne_marks": 0.75, "pigmentation": 0.6, "redness": 0.6, "comedons": 0.4},
        "skin_types": ["grasse", "mixte", "normale", "sensible"],
        "avoid_if": [],
        "conflicts_with": ["benzoyl_peroxide"],
        "family": "azelaic",
        "price_eur": 12.80,
        "irritation": 0.30,
        "evidence": {
            "level": "A",
            "note": "L'acide azélaïque est anti-inflammatoire, antibactérien, comédolytique et inhibiteur de la tyrosinase : c'est l'un des rares actifs à agir à la fois sur l'acné et sur les marques post-inflammatoires, y compris sur phototypes foncés.",
            "source": "Monographie acide azélaïque",
        },
        "url": "https://theordinary.com/fr-fr/azelaic-acid-suspension-10-serum-100405.html",
    },
    {
        "id": "the-ordinary-salicylic-acid-2-anhydrous",
        "name": "Salicylic Acid 2% Anhydrous Solution",
        "brand": "The Ordinary",
        "step": "traitement",
        "moment": "pm",
        "actives": [
            {"inci": "Salicylic Acid", "common": "acide salicylique (BHA)", "pct": 2.0},
        ],
        "targets": {"comedons": 0.8, "acne_active": 0.6, "pores": 0.6, "sebum": 0.4, "texture": 0.4},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": ["allergie_aspirine", "peau_tres_sensible", "grossesse"],
        "conflicts_with": ["retinoid", "benzoyl_peroxide"],
        "family": "bha",
        "price_eur": 9.20,
        "irritation": 0.45,
        "evidence": {
            "level": "A",
            "note": "Acide salicylique à 2 %, dosage de référence des exfoliants BHA en cosmétique : action comédolytique documentée sur l'acné rétentionnelle.",
            "source": "Recommandations acné - Société Française de Dermatologie",
        },
        "url": "https://theordinary.com/fr-fr/salicylic-acid-2-anhydrous-solution-serum-100477.html",
    },
    {
        "id": "the-ordinary-granactive-retinoid-2",
        "name": "Granactive Retinoid 2% in Squalane",
        "brand": "The Ordinary",
        "step": "traitement",
        "moment": "pm",
        "actives": [
            {"inci": "Hydroxypinacolone Retinoate", "common": "rétinoïde nouvelle génération", "pct": 2.0},
            {"inci": "Squalane", "common": "squalane", "pct": None},
        ],
        "targets": {"comedons": 0.7, "acne_active": 0.6, "texture": 0.7, "post_acne_marks": 0.5, "aging": 0.6, "pores": 0.5},
        "skin_types": ["grasse", "mixte", "normale", "seche"],
        "avoid_if": ["grossesse", "allaitement", "peau_tres_sensible", "rosacee"],
        "conflicts_with": ["benzoyl_peroxide", "aha", "bha"],
        "family": "retinoid",
        "price_eur": 12.90,
        "irritation": 0.55,
        "evidence": {
            "level": "A",
            "note": "Les rétinoïdes topiques normalisent la kératinisation folliculaire et constituent le socle du traitement de l'acné rétentionnelle ; contre-indication de principe pendant la grossesse pour toute la classe.",
            "source": "Recommandations acné - Société Française de Dermatologie",
        },
        "url": "https://theordinary.com/fr-fr/granactive-retinoid-2-emulsion-serum-100418.html",
    },
    {
        "id": "vichy-normaderm-sos-pate-soufre",
        "name": "Normaderm S.O.S Pâte Anti-Boutons au Soufre",
        "brand": "Vichy",
        "step": "traitement",
        "moment": "pm",
        "actives": [
            {"inci": "Sulfur", "common": "soufre", "pct": 10.0},
            {"inci": "Niacinamide", "common": "niacinamide", "pct": None},
            {"inci": "Glycolic Acid", "common": "acide glycolique", "pct": None},
        ],
        "targets": {"acne_active": 0.8, "sebum": 0.5, "comedons": 0.3},
        "skin_types": ["grasse", "mixte", "normale"],
        "avoid_if": ["peau_tres_sensible", "peau_lesee"],
        "conflicts_with": ["retinoid", "benzoyl_peroxide"],
        "family": None,
        "price_eur": 13.50,
        "irritation": 0.55,
        "evidence": {
            "level": "B",
            "note": "Le soufre topique a un usage historique documenté en dermatologie pour son action asséchante et antibactérienne sur les lésions inflammatoires ; les données modernes restent moins nombreuses que pour le peroxyde de benzoyle.",
            "source": "Monographie soufre topique - usage dermatologique",
        },
        "url": "https://www.vichy.fr/tous-les-produits/soins-de-la-peau/cremes-et-hydratants-visage/acne/normaderm-s-o-s-pate-anti-boutons-au-soufre",
    },
    {
        "id": "vichy-normaderm-probio-bha-serum",
        "name": "Normaderm Probio-BHA Sérum Anti-Imperfections",
        "brand": "Vichy",
        "step": "serum",
        "moment": "pm",
        "actives": [
            {"inci": "Salicylic Acid", "common": "acide salicylique (BHA)", "pct": None},
            {"inci": "Glycolic Acid", "common": "acide glycolique (AHA)", "pct": None},
            {"inci": "Lactobacillus Ferment", "common": "fractions de probiotiques", "pct": None},
        ],
        "targets": {"comedons": 0.7, "acne_active": 0.6, "pores": 0.6, "texture": 0.5, "sebum": 0.4},
        "skin_types": ["grasse", "mixte", "normale"],
        "avoid_if": ["allergie_aspirine", "peau_tres_sensible", "grossesse"],
        "conflicts_with": ["retinoid", "benzoyl_peroxide"],
        "family": "bha",
        "price_eur": 22.50,
        "irritation": 0.45,
        "evidence": {
            "level": "A",
            "note": "Sérum peeling quotidien reposant sur l'association BHA + AHA, dont l'effet comédolytique et sur le grain de peau est établi ; la partie probiotique relève de la revendication de marque.",
            "source": "Recommandations acné - Société Française de Dermatologie",
        },
        "url": "https://www.vichy.fr/tous-les-produits/soins-de-la-peau/serums-pour-le-visage/acne/normaderm-serum-probio-bha-anti-imperfections",
    },
    {
        "id": "ducray-keracnyl-pp-plus",
        "name": "Keracnyl PP+ Crème Anti-Imperfections",
        "brand": "Ducray",
        "step": "traitement",
        "moment": "both",
        "actives": [
            {"inci": "Niacinamide", "common": "niacinamide (vitamine PP)", "pct": None},
            {"inci": "Tripterygium Wilfordii Root Extract (Celastrol)", "common": "célastrol", "pct": None},
            {"inci": "Myrtus Communis Leaf Extract (Myrtacine)", "common": "myrtacine", "pct": None},
            {"inci": "Glyceryl Laurate (Monolaurin)", "common": "monolaurine", "pct": None},
        ],
        "targets": {"acne_active": 0.7, "redness": 0.5, "sensitivity": 0.4, "sebum": 0.4, "barrier_damage": 0.3},
        "skin_types": ["grasse", "mixte", "sensible"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "niacinamide",
        "price_eur": 13.50,
        "irritation": 0.15,
        "evidence": {
            "level": "A",
            "note": "Formulé autour de la niacinamide, actif anti-inflammatoire à preuve clinique établie en acné ; positionné pour les peaux irritées par un traitement asséchant.",
            "source": "Données cliniques sur la niacinamide topique",
        },
        "url": "https://www.ducray.com/fr-fr/f/produits/keracnyl-peaux-grasses-ou-a-tendance-acneique",
    },
    {
        "id": "ducray-keracnyl-serum",
        "name": "Keracnyl Sérum Anti-Imperfections",
        "brand": "Ducray",
        "step": "serum",
        "moment": "pm",
        "actives": [
            {"inci": "Azelaic Acid", "common": "acide azélaïque", "pct": None},
            {"inci": "Salicylic Acid", "common": "acide salicylique", "pct": None},
            {"inci": "Myrtus Communis Leaf Extract (Myrtacine)", "common": "myrtacine", "pct": None},
        ],
        "targets": {"acne_active": 0.7, "post_acne_marks": 0.7, "texture": 0.5, "aging": 0.3, "comedons": 0.4},
        "skin_types": ["grasse", "mixte", "normale"],
        "avoid_if": ["allergie_aspirine"],
        "conflicts_with": ["benzoyl_peroxide"],
        "family": "azelaic",
        "price_eur": 21.90,
        "irritation": 0.30,
        "evidence": {
            "level": "A",
            "note": "L'acide azélaïque agit à la fois sur les lésions d'acné et sur les marques pigmentaires résiduelles ; ciblé ici sur l'acné de la femme adulte.",
            "source": "Monographie acide azélaïque",
        },
        "url": "https://www.ducray.com/fr-fr/f/produits/keracnyl-peaux-grasses-ou-a-tendance-acneique",
    },
    {
        "id": "aderma-biology-ac-global",
        "name": "Biology AC (ex Phys-AC) Global Soin Anti-Imperfections",
        "brand": "A-Derma",
        "step": "traitement",
        "moment": "both",
        "actives": [
            {"inci": "Avena Sativa (Rhealba Oat) Extract", "common": "avoine Rhealba", "pct": None},
            {"inci": "Lactic Acid", "common": "acide lactique (AHA)", "pct": None},
            {"inci": "Garcinia Mangostana Extract", "common": "garcinia", "pct": None},
        ],
        "targets": {"acne_active": 0.6, "comedons": 0.5, "sebum": 0.5, "sensitivity": 0.4, "texture": 0.4},
        "skin_types": ["grasse", "mixte", "sensible"],
        "avoid_if": [],
        "conflicts_with": ["retinoid"],
        "family": "aha",
        "price_eur": 16.50,
        "irritation": 0.30,
        "evidence": {
            "level": "B",
            "note": "Exfoliation douce par acide lactique (AHA) sur base apaisante à l'avoine Rhealba ; les AHA ont une preuve établie sur la texture, l'avoine relève de la tolérance.",
            "source": "Monographie acides alpha-hydroxylés (AHA) topiques",
        },
        "url": "https://www.aderma.fr/fr-fr/f/l/biology-ac",
    },
    {
        "id": "noreva-exfoliac-acnomega-200",
        "name": "Exfoliac Acnomega 200",
        "brand": "Noreva",
        "step": "traitement",
        "moment": "both",
        "actives": [
            {"inci": "Glycolic Acid", "common": "acide glycolique (AHA)", "pct": None},
            {"inci": "Lactic Acid", "common": "acide lactique (AHA)", "pct": None},
            {"inci": "Omega HA complex", "common": "complexe Omega HA", "pct": None},
        ],
        "targets": {"comedons": 0.75, "acne_active": 0.6, "sebum": 0.5, "pores": 0.5, "texture": 0.5},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": ["peau_tres_sensible", "grossesse"],
        "conflicts_with": ["retinoid", "benzoyl_peroxide", "bha"],
        "family": "aha",
        "price_eur": 15.90,
        "irritation": 0.45,
        "evidence": {
            "level": "B",
            "note": "Soin correcteur pour imperfections modérées à base de dérivés d'AHA/BHA ; la classe AHA a des preuves solides, le complexe propriétaire de la marque non.",
            "source": "Monographie acides alpha-hydroxylés (AHA) topiques",
        },
        "url": "https://www.noreva-laboratoires.com/gammes/exfoliac",
    },
    {
        "id": "topicrem-ac-soin-actif",
        "name": "AC Soin Actif Anti-Imperfections",
        "brand": "Topicrem",
        "step": "traitement",
        "moment": "both",
        "actives": [
            {"inci": "Zinc Gluconate", "common": "gluconate de zinc", "pct": None},
            {"inci": "Fruit Acid Esters", "common": "esters de fruits kératolytiques", "pct": None},
            {"inci": "Sodium Hyaluronate", "common": "acide hyaluronique", "pct": None},
        ],
        "targets": {"acne_active": 0.55, "sebum": 0.55, "post_acne_marks": 0.4, "comedons": 0.4},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "zinc",
        "price_eur": 12.90,
        "irritation": 0.25,
        "evidence": {
            "level": "B",
            "note": "Soin séborégulateur au zinc à prix accessible ; le zinc topique dispose de données cliniques réelles mais moins nombreuses que les kératolytiques.",
            "source": "Monographie zinc topique - usage séborégulateur",
        },
        "url": "https://www.topicrem.com/fr/gammes/ac-control",
    },

    # =====================================================================
    # SÉRUMS — MARQUES POST-ACNÉ / PIGMENTATION / ÉCLAT
    # =====================================================================
    {
        "id": "lrp-mela-b3-serum",
        "name": "Mela B3 Sérum Anti-Taches",
        "brand": "La Roche-Posay",
        "step": "serum",
        "moment": "both",
        "actives": [
            {"inci": "Niacinamide", "common": "niacinamide", "pct": 10.0},
            {"inci": "Melasyl", "common": "Melasyl (actif anti-taches breveté)", "pct": None},
        ],
        "targets": {"post_acne_marks": 0.9, "pigmentation": 0.9, "dullness": 0.5, "sebum": 0.3},
        "skin_types": ["grasse", "mixte", "normale", "seche", "sensible"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "niacinamide",
        "price_eur": 44.90,
        "irritation": 0.20,
        "evidence": {
            "level": "A",
            "note": "La niacinamide à 10 % agit sur le transfert des mélanosomes et l'hyperpigmentation post-inflammatoire, avec des données d'essais randomisés ; le Melasyl est un actif propriétaire récent aux données majoritairement fournies par le laboratoire.",
            "source": "Données cliniques sur la niacinamide topique",
        },
        "url": "https://www.laroche-posay.fr/produits",
    },
    {
        "id": "eucerin-dermopure-triple-effect-serum",
        "name": "DermoPure Sérum Triple Action",
        "brand": "Eucerin",
        "step": "serum",
        "moment": "both",
        "actives": [
            {"inci": "Salicylic Acid", "common": "acide salicylique (BHA)", "pct": 2.0},
            {"inci": "Isobutylamido Thiazolyl Resorcinol (Thiamidol)", "common": "Thiamidol", "pct": None},
            {"inci": "Glycyrrhiza Inflata Root Extract", "common": "licochalcone A", "pct": None},
        ],
        "targets": {"post_acne_marks": 0.85, "acne_active": 0.6, "pigmentation": 0.7, "comedons": 0.5, "redness": 0.3},
        "skin_types": ["grasse", "mixte", "normale"],
        "avoid_if": ["allergie_aspirine", "peau_tres_sensible"],
        "conflicts_with": ["retinoid", "benzoyl_peroxide"],
        "family": "bha",
        "price_eur": 24.90,
        "irritation": 0.40,
        "evidence": {
            "level": "A",
            "note": "Acide salicylique à 2 % (preuve établie en acné rétentionnelle) associé au Thiamidol, inhibiteur de tyrosinase pour lequel le laboratoire a publié des données cliniques sur l'hyperpigmentation.",
            "source": "Recommandations acné - Société Française de Dermatologie ; monographie inhibiteurs de tyrosinase",
        },
        "url": "https://www.eucerin.fr/nos-produits/dermopure",
    },
    {
        "id": "eucerin-anti-pigment-dual-serum",
        "name": "Anti-Pigment Dual Sérum",
        "brand": "Eucerin",
        "step": "serum",
        "moment": "both",
        "actives": [
            {"inci": "Isobutylamido Thiazolyl Resorcinol (Thiamidol)", "common": "Thiamidol", "pct": None},
            {"inci": "Sodium Hyaluronate", "common": "acide hyaluronique", "pct": None},
        ],
        "targets": {"pigmentation": 0.9, "post_acne_marks": 0.8, "dullness": 0.5},
        "skin_types": ["normale", "mixte", "grasse", "seche", "sensible"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": None,
        "price_eur": 34.90,
        "irritation": 0.15,
        "evidence": {
            "level": "B",
            "note": "Le Thiamidol est un inhibiteur de la tyrosinase humaine développé par le laboratoire, avec des données cliniques publiées sur les taches ; alternative non irritante à l'hydroquinone, indisponible en cosmétique en Europe.",
            "source": "Monographie inhibiteurs de tyrosinase - dépigmentants cosmétiques",
        },
        "url": "https://www.eucerin.fr/nos-produits/anti-pigment",
    },
    {
        "id": "svr-sebiaclear-hydra",
        "name": "Sebiaclear Hydra Soin Réparateur Anti-Marques",
        "brand": "SVR",
        "step": "hydratant",
        "moment": "both",
        "actives": [
            {"inci": "Niacinamide", "common": "niacinamide", "pct": 5.0},
            {"inci": "Ceramides", "common": "céramides oméga", "pct": 8.0},
            {"inci": "Sodium Hyaluronate", "common": "acide hyaluronique", "pct": None},
        ],
        "targets": {"post_acne_marks": 0.7, "barrier_damage": 0.8, "dehydration": 0.7, "redness": 0.5, "sensitivity": 0.5},
        "skin_types": ["grasse", "mixte", "sensible", "seche"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "niacinamide",
        "price_eur": 16.90,
        "irritation": 0.08,
        "evidence": {
            "level": "A",
            "note": "Niacinamide à 5 % (dosage largement étudié pour l'action anti-inflammatoire et sur les marques rouges) associée à des céramides qui restaurent la barrière abîmée par les traitements desséchants.",
            "source": "Données cliniques sur la niacinamide topique",
        },
        "url": "https://fr.svr.com/collections/sebiaclear",
    },
    {
        "id": "lrp-pure-vitamin-c10-serum",
        "name": "Pure Vitamin C10 Sérum",
        "brand": "La Roche-Posay",
        "step": "serum",
        "moment": "am",
        "actives": [
            {"inci": "Ascorbic Acid", "common": "vitamine C pure", "pct": 10.0},
            {"inci": "Salicylic Acid", "common": "acide salicylique", "pct": None},
            {"inci": "Neurosensine", "common": "Neurosensine (apaisant)", "pct": None},
        ],
        "targets": {"dullness": 0.8, "texture": 0.6, "aging": 0.6, "pigmentation": 0.5, "post_acne_marks": 0.4},
        "skin_types": ["normale", "mixte", "grasse", "seche"],
        "avoid_if": ["peau_tres_sensible"],
        "conflicts_with": ["benzoyl_peroxide", "retinoid"],
        "family": "vitamin_c",
        "price_eur": 36.90,
        "irritation": 0.40,
        "evidence": {
            "level": "A",
            "note": "Acide ascorbique pur à 10 % : forme la plus étudiée de la vitamine C topique, avec un effet antioxydant et sur l'éclat démontré ; peut piquer sur peau réactive.",
            "source": "Monographie vitamine C topique (acide ascorbique et dérivés)",
        },
        "url": "https://www.laroche-posay.fr/produits",
    },
    {
        "id": "the-ordinary-hyaluronic-acid-2-b5",
        "name": "Hyaluronic Acid 2% + B5",
        "brand": "The Ordinary",
        "step": "serum",
        "moment": "both",
        "actives": [
            {"inci": "Sodium Hyaluronate", "common": "acide hyaluronique", "pct": 2.0},
            {"inci": "Panthenol", "common": "panthénol (vitamine B5)", "pct": None},
        ],
        "targets": {"dehydration": 0.8, "barrier_damage": 0.3, "dullness": 0.2},
        "skin_types": ["grasse", "mixte", "normale", "seche", "sensible"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "hyaluronic",
        "price_eur": 9.90,
        "irritation": 0.05,
        "evidence": {
            "level": "B",
            "note": "L'acide hyaluronique topique augmente l'hydratation de la couche cornée de façon mesurable ; effet de surface, à sceller par une crème pour durer, sans action sur l'acné.",
            "source": "Données cliniques sur les humectants topiques (acide hyaluronique)",
        },
        "url": "https://theordinary.com/fr-fr/hyaluronic-acid-2-b5-hydrating-serum-100418.html",
    },

    # =====================================================================
    # HYDRATANTS — du plus léger au plus riche
    # =====================================================================
    {
        "id": "lrp-effaclar-h-iso-biome",
        "name": "Effaclar H Iso-Biome Crème Hydratante Apaisante",
        "brand": "La Roche-Posay",
        "step": "hydratant",
        "moment": "both",
        "actives": [
            {"inci": "Niacinamide", "common": "niacinamide", "pct": None},
            {"inci": "Ceramide NP", "common": "céramides", "pct": None},
            {"inci": "Aqua Posae Filiformis", "common": "extrait de biomasse thermale", "pct": None},
        ],
        "targets": {"barrier_damage": 0.8, "dehydration": 0.7, "sensitivity": 0.6, "redness": 0.4, "acne_active": 0.2},
        "skin_types": ["grasse", "mixte", "sensible", "seche"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "ceramide",
        "price_eur": 17.50,
        "irritation": 0.05,
        "evidence": {
            "level": "B",
            "note": "Hydratant de compensation conçu pour les peaux acnéiques sous traitement asséchant ; céramides et niacinamide soutiennent la restauration de la barrière, ce qui améliore l'observance des traitements irritants.",
            "source": "Données cliniques sur les céramides topiques et la fonction barrière",
        },
        "url": "https://www.laroche-posay.fr/gammes/visage/effaclar",
    },
    {
        "id": "eucerin-dermopure-oil-control-fluide",
        "name": "DermoPure Oil Control Fluide Matifiant",
        "brand": "Eucerin",
        "step": "hydratant",
        "moment": "am",
        "actives": [
            {"inci": "Glycyrrhiza Inflata Root Extract", "common": "licochalcone A", "pct": None},
            {"inci": "Carnitine", "common": "L-carnitine", "pct": None},
            {"inci": "Decylene Glycol", "common": "décylène glycol", "pct": None},
        ],
        "targets": {"sebum": 0.8, "pores": 0.5, "acne_active": 0.4, "dehydration": 0.4, "redness": 0.3},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "soothing",
        "price_eur": 18.90,
        "irritation": 0.10,
        "evidence": {
            "level": "B",
            "note": "Fluide matifiant non comédogène : la L-carnitine et le décylène glycol disposent de données de marque sur le sébum et la flore cutanée, la licochalcone A d'un effet anti-inflammatoire documenté.",
            "source": "Monographie licochalcone A - actif anti-inflammatoire topique",
        },
        "url": "https://www.eucerin.fr/nos-produits/dermopure",
    },
    {
        "id": "bioderma-sebium-hydra",
        "name": "Sébium Hydra Crème Compensatrice",
        "brand": "Bioderma",
        "step": "hydratant",
        "moment": "both",
        "actives": [
            {"inci": "Glycerin", "common": "glycérine", "pct": None},
            {"inci": "Xylitol / Rhamnose", "common": "complexe hydratant", "pct": None},
        ],
        "targets": {"dehydration": 0.8, "barrier_damage": 0.7, "sensitivity": 0.5},
        "skin_types": ["grasse", "mixte", "sensible"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "soothing",
        "price_eur": 15.90,
        "irritation": 0.05,
        "evidence": {
            "level": "B",
            "note": "Crème de compensation pour peaux grasses desséchées par un traitement anti-acnéique : les humectants et émollients réduisent la xérose iatrogène, ce qui améliore la tolérance du traitement.",
            "source": "Recommandations acné - Société Française de Dermatologie (soins adjuvants)",
        },
        "url": "https://www.bioderma.fr/c/tous-les-produits/sebium",
    },
    {
        "id": "cerave-lotion-hydratante-visage",
        "name": "Crème Hydratante Visage",
        "brand": "CeraVe",
        "step": "hydratant",
        "moment": "both",
        "actives": [
            {"inci": "Ceramide NP / AP / EOP", "common": "céramides essentiels", "pct": None},
            {"inci": "Sodium Hyaluronate", "common": "acide hyaluronique", "pct": None},
            {"inci": "Niacinamide", "common": "niacinamide", "pct": None},
        ],
        "targets": {"dehydration": 0.8, "barrier_damage": 0.8, "sensitivity": 0.4},
        "skin_types": ["normale", "seche", "mixte", "sensible"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "ceramide",
        "price_eur": 13.90,
        "irritation": 0.05,
        "evidence": {
            "level": "B",
            "note": "Association céramides + acide hyaluronique avec technologie de libération progressive : les céramides topiques améliorent la fonction barrière de façon mesurable.",
            "source": "Données cliniques sur les céramides topiques et la fonction barrière",
        },
        "url": "https://www.cerave.fr/nos-produits/hydratants",
    },
    {
        "id": "cerave-baume-reparateur",
        "name": "Baume Réparateur (Healing Ointment)",
        "brand": "CeraVe",
        "step": "hydratant",
        "moment": "pm",
        "actives": [
            {"inci": "Petrolatum", "common": "vaseline", "pct": None},
            {"inci": "Ceramide NP", "common": "céramides", "pct": None},
            {"inci": "Panthenol", "common": "panthénol", "pct": None},
        ],
        "targets": {"barrier_damage": 0.95, "dehydration": 0.9, "sensitivity": 0.6},
        "skin_types": ["seche", "sensible"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "ceramide",
        "price_eur": 9.90,
        "irritation": 0.03,
        "evidence": {
            "level": "B",
            "note": "Baume occlusif à appliquer en couche fine et localisée sur les zones décapées ; l'occlusion est la façon la mieux documentée de limiter la perte en eau transépidermique.",
            "source": "Données cliniques sur les émollients occlusifs",
        },
        "url": "https://www.cerave.fr/nos-produits/hydratants",
    },
    {
        "id": "uriage-bariederm-cica-creme",
        "name": "Bariéderm Cica-Crème",
        "brand": "Uriage",
        "step": "hydratant",
        "moment": "both",
        "actives": [
            {"inci": "Zinc Sulfate / Copper Sulfate", "common": "sels de cuivre-zinc", "pct": None},
            {"inci": "Poly-2P (Uriage patent)", "common": "complexe réparateur", "pct": None},
            {"inci": "Uriage Thermal Water", "common": "eau thermale d'Uriage", "pct": None},
        ],
        "targets": {"barrier_damage": 0.9, "sensitivity": 0.7, "redness": 0.5, "dehydration": 0.6},
        "skin_types": ["seche", "sensible", "normale", "mixte"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "zinc",
        "price_eur": 13.90,
        "irritation": 0.03,
        "evidence": {
            "level": "B",
            "note": "Crème barrière aux sels de cuivre-zinc pour peaux fragilisées ou irritées par un actif fort ; le zinc topique a des données réelles en réparation cutanée.",
            "source": "Monographie zinc topique - réparation cutanée",
        },
        "url": "https://www.uriage.com/fr/fr/gammes/bariederm",
    },
    {
        "id": "noreva-exfoliac-nc-gel",
        "name": "Exfoliac NC Gel Hydratant Matifiant",
        "brand": "Noreva",
        "step": "hydratant",
        "moment": "am",
        "actives": [
            {"inci": "Glycerin", "common": "glycérine", "pct": None},
            {"inci": "Zinc Gluconate", "common": "gluconate de zinc", "pct": None},
        ],
        "targets": {"sebum": 0.6, "dehydration": 0.6, "pores": 0.3},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "zinc",
        "price_eur": 13.50,
        "irritation": 0.08,
        "evidence": {
            "level": "C",
            "note": "Gel hydratant oil-free pour peaux grasses : intérêt de texture (non comédogène, effet matifiant), pas d'actif anti-acnéique à preuve forte.",
            "source": "Composition publiée par la marque",
        },
        "url": "https://www.noreva-laboratoires.com/gammes/exfoliac",
    },

    # =====================================================================
    # APAISANTS / RÉPARATEURS — PEAU RÉACTIVE
    # =====================================================================
    {
        "id": "lrp-cicaplast-baume-b5",
        "name": "Cicaplast Baume B5+",
        "brand": "La Roche-Posay",
        "step": "hydratant",
        "moment": "both",
        "actives": [
            {"inci": "Panthenol", "common": "panthénol (pro-vitamine B5)", "pct": 5.0},
            {"inci": "Madecassoside", "common": "madécassoside (centella)", "pct": None},
            {"inci": "Zinc / Copper / Manganese", "common": "complexe cuivre-zinc-manganèse", "pct": None},
        ],
        "targets": {"barrier_damage": 0.9, "sensitivity": 0.8, "redness": 0.6, "dehydration": 0.7, "post_acne_marks": 0.3},
        "skin_types": ["seche", "sensible", "normale", "mixte"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "soothing",
        "price_eur": 11.50,
        "irritation": 0.03,
        "evidence": {
            "level": "B",
            "note": "Panthénol à 5 % : effet hydratant et de soutien de la réparation épidermique documenté par des études cliniques ; usage classique en accompagnement des traitements irritants.",
            "source": "Monographie panthénol (dexpanthénol) topique",
        },
        "url": "https://www.laroche-posay.fr/gammes/visage/cicaplast",
    },
    {
        "id": "avene-cicalfate-plus-creme-reparatrice",
        "name": "Cicalfate+ Crème Réparatrice Protectrice",
        "brand": "Avène",
        "step": "hydratant",
        "moment": "both",
        "actives": [
            {"inci": "Copper Sulfate / Zinc Sulfate", "common": "sulfates de cuivre et de zinc", "pct": None},
            {"inci": "C+Restore (postbiotique)", "common": "complexe postbiotique", "pct": None},
            {"inci": "Avene Aqua", "common": "eau thermale d'Avène", "pct": None},
        ],
        "targets": {"barrier_damage": 0.9, "sensitivity": 0.8, "redness": 0.6, "post_acne_marks": 0.3},
        "skin_types": ["seche", "sensible", "normale"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "zinc",
        "price_eur": 11.90,
        "irritation": 0.03,
        "evidence": {
            "level": "B",
            "note": "Crème réparatrice aux sels de cuivre-zinc, très utilisée après geste dermatologique ou sur peau irritée ; données cliniques réelles sur la cicatrisation superficielle.",
            "source": "Monographie zinc et cuivre topiques - réparation cutanée",
        },
        "url": "https://www.eau-thermale-avene.fr/peau-irritee/cicalfate",
    },
    {
        "id": "aderma-epitheliale-ah-ultra",
        "name": "Epithéliale A.H Ultra Crème Réparatrice",
        "brand": "A-Derma",
        "step": "hydratant",
        "moment": "both",
        "actives": [
            {"inci": "Avena Sativa (Rhealba Oat) Extract", "common": "avoine Rhealba", "pct": None},
            {"inci": "Sodium Hyaluronate", "common": "acide hyaluronique", "pct": None},
            {"inci": "Sucralfate", "common": "sucralfate", "pct": None},
        ],
        "targets": {"barrier_damage": 0.85, "sensitivity": 0.7, "redness": 0.5, "post_acne_marks": 0.3},
        "skin_types": ["seche", "sensible", "normale"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "soothing",
        "price_eur": 12.90,
        "irritation": 0.03,
        "evidence": {
            "level": "B",
            "note": "Soin réparateur post-agression (peeling, rétinoïde, frottement) ; l'avoine Rhealba et le sucralfate ont des données de tolérance et de réparation issues des travaux du laboratoire.",
            "source": "Documentation laboratoire + monographie émollients réparateurs",
        },
        "url": "https://www.aderma.fr/fr-fr/f/l/epitheliale-ah",
    },

    # =====================================================================
    # PROTECTIONS SOLAIRES
    # =====================================================================
    {
        "id": "lrp-anthelios-uvmune-400-fluide-invisible",
        "name": "Anthelios UVMune 400 Fluide Invisible SPF50+",
        "brand": "La Roche-Posay",
        "step": "protection",
        "moment": "am",
        "actives": [
            {"inci": "Mexoryl 400 (MCE) + filtres UVA/UVB", "common": "filtres solaires très haute protection", "pct": None},
        ],
        "targets": {"pigmentation": 0.8, "post_acne_marks": 0.7, "aging": 0.8, "dullness": 0.3},
        "skin_types": ["normale", "mixte", "grasse", "seche", "sensible"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "spf",
        "price_eur": 22.90,
        "irritation": 0.10,
        "evidence": {
            "level": "A",
            "note": "La photoprotection quotidienne est la mesure la mieux établie pour empêcher l'aggravation et la persistance des taches post-inflammatoires ; fini invisible sans effet blanc, compatible avec tous les phototypes.",
            "source": "Recommandations photoprotection - Société Française de Dermatologie",
        },
        "url": "https://www.laroche-posay.fr/gammes/solaires/anthelios/anthelios-uvmune-400-creme-solaire-fluide-invisible-spf50-/LRP_025.html",
    },
    {
        "id": "lrp-anthelios-uvmune-400-oil-control",
        "name": "Anthelios UVMune 400 Oil Control Gel-Crème SPF50+",
        "brand": "La Roche-Posay",
        "step": "protection",
        "moment": "am",
        "actives": [
            {"inci": "Mexoryl 400 (MCE) + filtres UVA/UVB", "common": "filtres solaires très haute protection", "pct": None},
            {"inci": "Airlicium", "common": "poudre absorbante matifiante", "pct": None},
        ],
        "targets": {"sebum": 0.6, "pigmentation": 0.8, "post_acne_marks": 0.7, "aging": 0.7, "pores": 0.3},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "spf",
        "price_eur": 22.90,
        "irritation": 0.12,
        "evidence": {
            "level": "A",
            "note": "Photoprotection SPF50+ en texture gel-crème matifiante non comédogène : indispensable sous exfoliants, rétinoïdes ou traitement anti-taches.",
            "source": "Recommandations photoprotection - Société Française de Dermatologie",
        },
        "url": "https://www.laroche-posay.fr/gammes/solaires/anthelios",
    },
    {
        "id": "avene-cleanance-solaire-spf50",
        "name": "Cleanance Solaire SPF50+",
        "brand": "Avène",
        "step": "protection",
        "moment": "am",
        "actives": [
            {"inci": "Filtres UVA/UVB", "common": "filtres solaires très haute protection", "pct": None},
            {"inci": "Glyceryl Laurate (Monolaurin)", "common": "monolaurine séborégulatrice", "pct": None},
        ],
        "targets": {"sebum": 0.6, "pigmentation": 0.7, "post_acne_marks": 0.7, "aging": 0.7, "acne_active": 0.2},
        "skin_types": ["grasse", "mixte", "sensible"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "spf",
        "price_eur": 19.90,
        "irritation": 0.12,
        "evidence": {
            "level": "A",
            "note": "SPF50+ formulé non comédogène pour peaux à imperfections ; la photoprotection prévient l'assombrissement des marques post-acné, phénomène majeur chez les phototypes intermédiaires à foncés.",
            "source": "Recommandations photoprotection - Société Française de Dermatologie",
        },
        "url": "https://www.eau-thermale-avene.fr/peau-a-imperfections/cleanance",
    },
    {
        "id": "bioderma-photoderm-nude-touch-spf50",
        "name": "Photoderm Nude Touch SPF50+ (teintes claire / dorée)",
        "brand": "Bioderma",
        "step": "protection",
        "moment": "am",
        "actives": [
            {"inci": "Filtres UVA/UVB + pigments minéraux", "common": "filtres solaires teintés", "pct": None},
        ],
        "targets": {"pigmentation": 0.8, "post_acne_marks": 0.7, "sebum": 0.5, "aging": 0.6, "redness": 0.3},
        "skin_types": ["grasse", "mixte", "normale"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "spf",
        "price_eur": 19.90,
        "irritation": 0.12,
        "evidence": {
            "level": "A",
            "note": "Solaire teinté au fini mat sans voile blanc, décliné en plusieurs teintes : les pigments apportent en plus une protection contre la lumière visible, pertinente pour les hyperpigmentations des phototypes foncés.",
            "source": "Recommandations photoprotection - Société Française de Dermatologie",
        },
        "url": "https://www.bioderma.fr/nos-produits/photoderm",
    },
    {
        "id": "uriage-hyseac-3-regul-spf50",
        "name": "Hyséac 3-Regul+ Soin Global SPF50+",
        "brand": "Uriage",
        "step": "protection",
        "moment": "am",
        "actives": [
            {"inci": "Filtres UVA/UVB", "common": "filtres solaires très haute protection", "pct": None},
            {"inci": "Glycyrrhiza Glabra Root Extract", "common": "extrait de réglisse", "pct": None},
            {"inci": "Uriage Thermal Water", "common": "eau thermale d'Uriage", "pct": None},
        ],
        "targets": {"sebum": 0.6, "acne_active": 0.4, "post_acne_marks": 0.6, "pigmentation": 0.7, "pores": 0.4},
        "skin_types": ["grasse", "mixte", "sensible"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "spf",
        "price_eur": 15.15,
        "irritation": 0.12,
        "evidence": {
            "level": "A",
            "note": "Soin anti-imperfections doublé d'un SPF50+ : deux gestes en un, utile pour l'observance chez les 16-25 ans qui sautent souvent l'étape solaire.",
            "source": "Recommandations photoprotection - Société Française de Dermatologie",
        },
        "url": "https://www.uriage.com/fr/fr/gammes/hyseac",
    },
    {
        "id": "eucerin-sun-oil-control-gel-creme-spf50",
        "name": "Sun Oil Control Gel-Crème SPF50+",
        "brand": "Eucerin",
        "step": "protection",
        "moment": "am",
        "actives": [
            {"inci": "Filtres UVA/UVB", "common": "filtres solaires très haute protection", "pct": None},
            {"inci": "Carnitine", "common": "L-carnitine", "pct": None},
            {"inci": "Glycyrrhiza Inflata Root Extract", "common": "licochalcone A", "pct": None},
        ],
        "targets": {"sebum": 0.8, "pigmentation": 0.7, "post_acne_marks": 0.6, "aging": 0.6},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": [],
        "conflicts_with": [],
        "family": "spf",
        "price_eur": 18.90,
        "irritation": 0.12,
        "evidence": {
            "level": "A",
            "note": "SPF50+ à fini ultra-mat pour peaux très grasses ; la licochalcone A ajoute un effet anti-inflammatoire documenté sur l'érythème.",
            "source": "Recommandations photoprotection - Société Française de Dermatologie",
        },
        "url": "https://www.eucerin.fr/nos-produits/sun-protection",
    },

    # =====================================================================
    # MASQUES
    # =====================================================================
    {
        "id": "lrp-effaclar-masque-purifiant",
        "name": "Effaclar Masque Purifiant Sébo-Régulateur",
        "brand": "La Roche-Posay",
        "step": "masque",
        "moment": "pm",
        "actives": [
            {"inci": "Kaolin / Argilla", "common": "argiles absorbantes", "pct": None},
            {"inci": "Panthenol", "common": "panthénol", "pct": 5.0},
        ],
        "targets": {"sebum": 0.8, "pores": 0.6, "comedons": 0.4},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": ["peau_tres_sensible"],
        "conflicts_with": [],
        "family": "soothing",
        "price_eur": 16.90,
        "irritation": 0.20,
        "evidence": {
            "level": "B",
            "note": "Masque à l'argile : absorption mécanique du sébum de surface, effet immédiat mais transitoire ; le panthénol à 5 % limite l'effet desséchant.",
            "source": "Monographie panthénol (dexpanthénol) topique ; usage cosmétique des argiles",
        },
        "url": "https://www.laroche-posay.fr/gammes/visage/effaclar",
    },
    {
        "id": "avene-cleanance-mask",
        "name": "Cleanance Mask Masque-Gommage",
        "brand": "Avène",
        "step": "masque",
        "moment": "pm",
        "actives": [
            {"inci": "Perlite / Kaolin", "common": "poudres absorbantes et exfoliantes", "pct": None},
            {"inci": "Glycolic Acid", "common": "acide glycolique", "pct": None},
            {"inci": "Avene Aqua", "common": "eau thermale d'Avène", "pct": None},
        ],
        "targets": {"sebum": 0.7, "pores": 0.6, "comedons": 0.6, "texture": 0.5},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": ["peau_tres_sensible", "peau_lesee"],
        "conflicts_with": ["retinoid", "benzoyl_peroxide"],
        "family": "aha",
        "price_eur": 15.90,
        "irritation": 0.35,
        "evidence": {
            "level": "B",
            "note": "Double action masque + gommage : l'AHA apporte l'exfoliation chimique à preuve établie, l'exfoliation mécanique est à éviter en poussée inflammatoire.",
            "source": "Monographie acides alpha-hydroxylés (AHA) topiques",
        },
        "url": "https://www.eau-thermale-avene.fr/peau-a-imperfections/cleanance",
    },
    {
        "id": "ducray-keracnyl-mask",
        "name": "Keracnyl Masque Triple Action",
        "brand": "Ducray",
        "step": "masque",
        "moment": "pm",
        "actives": [
            {"inci": "Kaolin", "common": "argile blanche", "pct": None},
            {"inci": "Salicylic Acid", "common": "acide salicylique", "pct": None},
            {"inci": "Myrtus Communis Leaf Extract (Myrtacine)", "common": "myrtacine", "pct": None},
        ],
        "targets": {"sebum": 0.75, "pores": 0.6, "comedons": 0.5, "acne_active": 0.3},
        "skin_types": ["grasse", "mixte"],
        "avoid_if": ["allergie_aspirine", "peau_tres_sensible"],
        "conflicts_with": ["benzoyl_peroxide"],
        "family": "bha",
        "price_eur": 14.90,
        "irritation": 0.30,
        "evidence": {
            "level": "B",
            "note": "Masque argile + acide salicylique : l'AS apporte le seul actif à preuve forte, l'argile un effet matifiant immédiat sur le sébum de surface.",
            "source": "Recommandations acné - Société Française de Dermatologie",
        },
        "url": "https://www.ducray.com/fr-fr/f/produits/keracnyl-peaux-grasses-ou-a-tendance-acneique",
    },
]
